### PR TITLE
Redmine 26096 - Implement the mapping of the ANTS application number to a specific Form field, in the task config

### PR DESCRIPTION
**Pull request by atos-mohamed-b**
- Updated the configuration task to allow the selection of a field from a specific Form. The value of the ANTS application number will be retrieved from that field when the task is executed

- Modified some classes to make them more generic

- Updated the SQL Table and the related services, DAO...

Link to the related Redmine issue:

- https://dev.lutece.paris.fr/bugtracker/issues/26096

### CODE REVIEW

**Comment by NLG85** [comment]
Could you please resolve the conflicts in this branch ?

**Comment by atos-mohamed-b** [comment]
Hi @NLG85, the conflicts have now been resolved

**Review by FrancoisEricMerlin — COMMENTED** [review]
why they are 6 commits for add a blank in this file ?

**Comment by atos-mohamed-b** [comment]
Hi @FrancoisEricMerlin. The content of this PR was also in the following PR:
- https://github.com/lutece-secteur-public/gru-module-workflow-appointmentants/pull/3

The PR #3 has been merged, making this one redundant.

**Pull request closed without merging**
